# Generated by Django 2.1.2 on 2018-10-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
