# Generated by Django 2.1.2 on 2018-10-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='id',
        ),
        migrations.AddField(
            model_name='userlog',
            name='userlogid',
            field=models.AutoField(default=23, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
