# Generated by Django 2.1.2 on 2018-10-29 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0002_auto_20181026_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('load_weight', models.CharField(max_length=150)),
                ('payment_status', models.CharField(max_length=150)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Truck.UserLog')),
            ],
        ),
    ]
