# Generated by Django 2.1.2 on 2018-10-29 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0005_booking_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user_id',
        ),
    ]
