# Generated by Django 2.1.2 on 2018-10-30 09:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0006_remove_booking_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=150)),
                ('driver_mobile', models.CharField(max_length=150)),
                ('driver_email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('routeid', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('start', models.CharField(max_length=150)),
                ('int_st2', models.CharField(max_length=150)),
                ('int_st3', models.CharField(max_length=150)),
                ('int_st4', models.CharField(max_length=150)),
                ('end', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Truck_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.CharField(max_length=150)),
                ('arriving_date', models.CharField(max_length=150)),
                ('truck_weight', models.IntegerField()),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Truck.Routes')),
            ],
        ),
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('truck_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('max_load', models.IntegerField()),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Truck.Drivers')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='date_booked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='date_journey',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Truck.UserLog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlog',
            name='date_registered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='load_weight',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='truck_status',
            name='truck_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Truck.Trucks'),
        ),
        migrations.AddField(
            model_name='booking',
            name='route_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Truck.Routes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='truck_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Truck.Trucks'),
            preserve_default=False,
        ),
    ]
