# Generated by Django 2.1.3 on 2018-11-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Truck', '0008_auto_20181108_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_journey',
            field=models.DateField(),
        ),
    ]
